### ISSUE TITLE
Normal card play rule not enforced

### ISSUE THREAD

**Issue by datanoh** [trekcc-ops/gemp-stccg#108]
I can play an unlimited number of cards during the play phase.

(Easy to not notice this in the client if your deck only includes copies of one unique personnel.)

**Comment by andrewd18** [comment]
I used `git bisect` to determine when this occurred, it first started happening as part of #80, so something in that PR caused this. I hope that helps narrow it down!

```
93a6cc53c5a0f10e6f149431198bb22a6a2779ca is the first bad commit

Game state serialization (#80)
```
