### ISSUE TITLE
Draw deck is alphabetical not shuffled

### ISSUE THREAD

**Issue by andrewd18** [trekcc-ops/gemp-stccg#112]
The draw deck is not shuffling before game start; instead, it is sorted alphabetically by type.

**Steps to reproduce:**
1. Create a valid 1E deck where one personnel starts with A, another with B, another with C, etc.
2. Run a game.
3. Seed missions, get to the hand draw phase.
4. Look at your hand.

**Expected Results:**
* The hand is a randomized subset of my draw deck.

**Actual Results:**
* The first seven cards will be the first seven personnel, alphabetically, of your deck.
* All future card draws will continue to be in alphabetical order.
* Once you get through all the personnel, then you move on to equipment, then ships, etc.  It appears to be alphabetical by type.

In the image below I played the left-most card in my hand, Alexander Rozhenko, and my card draw was a Deanna Troi who was right after a Christopher Hobson.
![image](https://github.com/user-attachments/assets/7e9c5ab2-672a-4409-a8d2-0029f8599a84)

Seen on `main`.

**Comment by datanoh** [comment]
Were you using the 1E Debug format? It skips shuffling for reproducibility.

**Comment by andrewd18** [comment]
Uhhhhh yes that could very much be it. Let me check.

**Comment by andrewd18** [comment]
Yep, that was it. Closing. Thanks for the insight.
