### ISSUE TITLE
Staffed ship is not staffed

### ISSUE THREAD

**Issue by andrewd18** [trekcc-ops/gemp-stccg#128]
As seen on `main`, commit id `721d10b518e1abfcd1bf5263f5bcbb7cec17ac6b` in a 1E Modern Complete game (not Debug):

I have a generic D'Deridex class ship staffed with Taris, D'Vin, and Mareth.

![image](https://github.com/user-attachments/assets/be96d098-7967-46e6-a881-9a1f463000ca)

When I select the ship, which should be staffed, I cannot undock it.

![image](https://github.com/user-attachments/assets/e7dadfad-0ec5-4c6c-936a-691dcdf7357f)

**Comment by andrewd18** [comment]
I added a second D'Vin and I was able to undock it; might be a problem with Mareth.

**Comment by datanoh** [comment]
It's definitely a problem with Mareth. Looks like a few of the cards in the Engage expansion are missing their staffing icons.

**Comment by datanoh** [comment]
Resolved by PR #130
