### ISSUE TITLE
Shared Missions

### ISSUE THREAD

**Issue by datanoh** [trekcc-ops/gemp-stccg#5]
Not certain if shared missions work the way they're supposed to:

**Back End**
Cards tend to associate with other physical cards, but there should be functionality for missions to be considered a conceptual object, so that both mission cards are impacted consistently. There may be some implications from the way this is currently handled already. Long-term missions should be considered a Mission object distinct from the card itself, similar to the AwayTeam class.

**Front End**
Shared missions should stack on top of each other rather than next to each other in the same div. (See the 1E rulebook for an example of how this should look.) This will have implications on how other items line up next to missions in the UI.

**Comment by eberlems** [comment]
This only affects unique missions with the same location name.
Some of these locations use upper case first and some don't. But they should be treated equal.
This also affects the opponent's side of attemptability and gametext of these cards.
I don't recall any lore based effects on current cards that make a difference.

**Comment by datanoh** [comment]
Thanks @eberlems! So far the location identifier in the code is case-sensitive. Are you saying it shouldn't be?

**Comment by eberlems** [comment]
https://www.trekcc.org/1e/?mode=search&submit=Search&edition=Tr1E&traits%5B%5D=Badlands+Region&showMission_region=1#Results
There is Class-M planetoid and Class-M Planetoid, similar Plasma storms and Plasma Storms, ...

**Comment by datanoh** [comment]
Resolved the server side issue here. Creating a new issue specifically for the client side.
