### ISSUE TITLE
Available cards in deck builder don't update when you change formats

### ISSUE THREAD

**Issue by datanoh** [trekcc-ops/gemp-stccg#93]
If you change the game format in the upper-left dropdown box:

![image](https://github.com/user-attachments/assets/715f3406-672a-4b8d-ab1b-4e64375c84ee)

The available cards on the right don't update accordingly. Shown below, the format has been changed to "2E All" but all the cards are still 1E cards.

![image](https://github.com/user-attachments/assets/27a4367d-8a10-4576-80e1-0b4df839a7fe)

**Comment by andrewd18** [comment]
Workaround: Toggle a faction affiliation icon.

**Comment by datanoh** [comment]
@andrewd18 Right - my guess is it shouldn't be too hard to refresh the pane on the right when the format is changed though?

No worries if we're not on the same page here. Feel free to remove it from MVP or unassign yourself, I'd just like to make the change at some point.

**Comment by datanoh** [comment]
@andrewd18 I also didn't intend to link it so directly to your pull request -- definitely no need to tie this to that PR if you don't think it's appropriate.
